/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAreasRouteImport } from './routes/admin.areas'
import { Route as AdminCodSurchargesRouteImport } from './routes/admin.cod-surcharges'
import { Route as AdminRatesRouteImport } from './routes/admin.rates'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AgentHistoryRouteImport } from './routes/agent.history'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AgentOrdersOrderIdRouteImport } from './routes/agent.orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAreasRoute = AdminAreasRouteImport.update({
  id: '/admin/areas',
  path: '/admin/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCodSurchargesRoute = AdminCodSurchargesRouteImport.update({
  id: '/admin/cod-surcharges',
  path: '/admin/cod-surcharges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRatesRoute = AdminRatesRouteImport.update({
  id: '/admin/rates',
  path: '/admin/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/admin/zones',
  path: '/admin/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentHistoryRoute = AgentHistoryRouteImport.update({
  id: '/agent/history',
  path: '/agent/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/admin/orders/$orderId',
  path: '/admin/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentOrdersOrderIdRoute = AgentOrdersOrderIdRouteImport.update({
  id: '/agent/orders/$orderId',
  path: '/agent/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/cod-surcharges': typeof AdminCodSurchargesRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/zones': typeof AdminZonesRoute
  '/agent/history': typeof AgentHistoryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/agent/orders/$orderId': typeof AgentOrdersOrderIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/cod-surcharges': typeof AdminCodSurchargesRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/zones': typeof AdminZonesRoute
  '/agent/history': typeof AgentHistoryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/agent/orders/$orderId': typeof AgentOrdersOrderIdRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/cod-surcharges': typeof AdminCodSurchargesRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/zones': typeof AdminZonesRoute
  '/agent/history': typeof AgentHistoryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/agent/orders/$orderId': typeof AgentOrdersOrderIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/areas'
    | '/admin/cod-surcharges'
    | '/admin/rates'
    | '/admin/zones'
    | '/agent/history'
    | '/orders/$orderId'
    | '/orders/new'
    | '/admin/'
    | '/agent/'
    | '/orders/'
    | '/admin/orders/$orderId'
    | '/agent/orders/$orderId'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/areas'
    | '/admin/cod-surcharges'
    | '/admin/rates'
    | '/admin/zones'
    | '/agent/history'
    | '/orders/$orderId'
    | '/orders/new'
    | '/admin'
    | '/agent'
    | '/orders'
    | '/admin/orders/$orderId'
    | '/agent/orders/$orderId'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/areas'
    | '/admin/cod-surcharges'
    | '/admin/rates'
    | '/admin/zones'
    | '/agent/history'
    | '/orders/$orderId'
    | '/orders/new'
    | '/admin/'
    | '/agent/'
    | '/orders/'
    | '/admin/orders/$orderId'
    | '/agent/orders/$orderId'
    | '/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminAreasRoute: typeof AdminAreasRoute
  AdminCodSurchargesRoute: typeof AdminCodSurchargesRoute
  AdminRatesRoute: typeof AdminRatesRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AgentHistoryRoute: typeof AgentHistoryRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentIndexRoute: typeof AgentIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AgentOrdersOrderIdRoute: typeof AgentOrdersOrderIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/areas': {
      id: '/admin/areas'
      path: '/admin/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AdminAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cod-surcharges': {
      id: '/admin/cod-surcharges'
      path: '/admin/cod-surcharges'
      fullPath: '/admin/cod-surcharges'
      preLoaderRoute: typeof AdminCodSurchargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rates': {
      id: '/admin/rates'
      path: '/admin/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AdminRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/history': {
      id: '/agent/history'
      path: '/agent/history'
      fullPath: '/agent/history'
      preLoaderRoute: typeof AgentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/orders/$orderId': {
      id: '/agent/orders/$orderId'
      path: '/agent/orders/$orderId'
      fullPath: '/agent/orders/$orderId'
      preLoaderRoute: typeof AgentOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminAreasRoute: AdminAreasRoute,
  AdminCodSurchargesRoute: AdminCodSurchargesRoute,
  AdminRatesRoute: AdminRatesRoute,
  AdminZonesRoute: AdminZonesRoute,
  AgentHistoryRoute: AgentHistoryRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentIndexRoute: AgentIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AgentOrdersOrderIdRoute: AgentOrdersOrderIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
